# Action to test the addition or change of a new kit
name: Kit Database Validation

on:
  # Triggers when a pull request is opened against the main branch
  pull_request:
    branches:
    - main

jobs:
  Validate:
    # We are just using python so lets use linux
    runs-on: ubuntu-latest

    steps:
      # Get the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python and install toml
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Initialize the project
      - name: Initialize Project
        run: |
          pip install toml==0.10.2

      # Get the version of the database.
      - name: Get Database Version
        run: |
          echo "KIT_VERSION=$(python -c 'from tools import utils; print(utils.get_version())')" >> $GITHUB_ENV

      # Run the build script to test the changes.
      - name: Run Build Script
        run: |
          python -m tools.build
          ls -l ./build

      # TODO: Run a test script to validate the database was generated correctly.